// 14-NextJs-Astro/AstroEx3/src/components/Counter.jsx
import {useState} from 'react'
export default function Counter(){
    const [count, setCount] = useState(0);

    const increment = ()=>setCount(count+1)
    const decrement = ()=>setCount(count-1)

    return (
        <div>
            <h3>A React component rendered with client:load (CSR)</h3>
            <h3>Count: {count}</h3>
            <button onClick={decrement}>Decrement</button>
            {'  '}
            <button onClick={increment}>Increment</button>
        </div>
    )
}

// 13-Angular-Vue-Svelte/07-Qwik/src/components/counter/counter.tsx
import { component$, useStore, useStylesScoped$ } from '@builder.io/qwik';
import styles from './counter.css?inline';

export default component$(() => {
  useStylesScoped$(styles);
  const store = useStore({ count: 0 });

  return (
    <div className="container">
      <p>Count: {store.count}</p>
      <p>
        <button onClick$={() => store.count--}>Decrement</button>
        <button onClick$={() => store.count++}>Increment</button>
      </p>
    </div>
  );
});
