// 8- React Conext-API/09-React-ContextAPI/03-ItemListAppWithContextAPI2/code/src/App.jsx
import React from 'react';
import './css/App.css';
import FilterItemForm from './components/FilterItemForm'
import AddItemForm from './components/AddItemForm'
import ItemList from './components/ItemList'
import ItemsContextProvider from './contexts/ItemsContext'

function App() {
  return (
    <ItemsContextProvider>
      <div className="container">
        <h1 className="header">ItemList App</h1>
        <FilterItemForm/>
        <AddItemForm/>
        <ItemList/>
      </div>
    </ItemsContextProvider>
  );
} //end-App

export default App;

// 13-Angular-Vue-Svelte/05-Svelte-item-list2/src/App.svelte
<script>
  import FilterItemForm from './comps/FilterItemForm.svelte'
  import AddItemForm from './comps/AddItemForm.svelte'
  import ItemList from './comps/ItemList.svelte'
</script>

<div class="container">
  <h1 class="header">ItemList App</h1>
  <FilterItemForm />
  <AddItemForm />
  <ItemList />
</div>
