// 13-Angular-Vue-Svelte/04-Svelte-item-list1/src/comps/AddItemForm.svelte
<script>
    export let addItem;
    let title = ''
    let displayErrorMsg = false;

    const onSubmit = (e) => {
        e.preventDefault();
    
        title = title.trim();
        
        if (title === ""){
            setTimeout(()=>{displayErrorMsg = false}, 1000);
           displayErrorMsg = true;
        } else {
            addItem(title)
        } //end-else

       title = '';
  } //end-onSubmit
</script>

<form id="AddItemForm" on:submit|preventDefault={(e)=>onSubmit(e)}>
    {#if displayErrorMsg}
        <div class="error">Please enter a title before pressing Submit</div>        
    {/if}

    <div>
        <label for="title"><strong>Item Title: </strong></label>
        <input type="text" bind:value={title}/>
    </div>
    <input class="btn" type="submit" value="Add Item"/>      
</form>

// 8- React Conext-API/09-React-ContextAPI/03-ItemListAppWithContextAPI2/code/src/components/AddItemForm.jsx
import React, { useState, useContext } from 'react'
import "../css/App.css"
import {ItemsContext} from '../contexts/ItemsContext'

function AddItemForm(props) {
  const [title, setTitle] = useState('');
  const [displayErrorMsg, setDisplayErrorMsg] = useState(false);
  const {addItem} = useContext(ItemsContext);

  const onChange = (e)=>{
    setTitle(e.target.value);
  } //end-onChange

  const onSubmit = (e) => {
    e.preventDefault();
    
    const tt = title.trim();
    
    if (tt === ""){
      setDisplayErrorMsg(true);
      setTimeout(()=>{setDisplayErrorMsg(false)}, 1000);
    } else {
      addItem(tt);
    } //end-else

    setTitle('');
  } //end-onSubmit

  // Render the item
  let errorMsgStyle = {display: "none"};
  if (displayErrorMsg) errorMsgStyle = {display: ""};

  return (
    <form id="AddItemForm" onSubmit={onSubmit}>
        <div className="error" style={errorMsgStyle}>Please enter a title before pressing Submit</div>
        <div>
          <label><strong>Item Title: </strong></label>
          <input type="text" value={title} onChange={onChange}/>
        </div>
        <input className="btn" type="submit" value="Add Item"/>      
      </form>
  );
} // end-AddItemForm

export default AddItemForm;
